EssenciaWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('FirstLevel.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

FirstLevel/urls.py
from django.urls import path
from . import views
from django.views.generic.base import TemplateView


app_name = 'basic_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='user_login'),
    # path('logged/', views.logged_in, name='logged_in'),
    path('logout/', views.user_logout, name='user_logout'),
    path('login1/', views.after_register, name='after_register'),
    path('clients/', views.clients, name='clients'),
    path('vision/', views.vision, name='vision'),
    path('principle/', views.principle, name='principle'),
    path('whatwedo/', views.whatwedo, name='whatwedo'),
    path('strength/', views.strength, name='strength'),
    # path('L_T_MIS/', views.L_T_MIS, name='L_T_MIS'),
    # path('L_T_BILLING/', views.L_T_BILLING, name='L_T_BILLING'),
    # path('L_T_SALARY/', views.MASTER_SALARY_TW, name='L_T_TW'),
    path('IDFC_TW_BILLING/', views.IDFC_TW_BILLING, name='IDFC_TW_BILLING'),
    path('login/IDFC_TW_MIS.html', views.IDFC_TW_MIS, name='IDFC_TW_MIS'),
    path('login/SLICE_CC_MIS.html', views.SLICE_MIS, name='SLICE_MIS'),
    path('IDFC_TW_SALARY/', views.MASTER_SALARY_TW, name='IDFC_TW_SALARY'),
    path('IDFC_TW_TC_SALARY/', views.IDFC_TW_SALARY_TC, name='IDFC_TW_SALARY_TC'),
    # path('L_T_TW_TC_SALARY/', views.L_T_TW_SALARY_TC, name='L_T_TW_SALARY_TC'),
    path('login/IDFC_HL_MIS.html', views.IDFC_HL_MIS, name='IDFC_HL_MIS'),
    path('MAGMA_FOS_SALARY/', views.MASTER_SALARY_MAGMA, name='MASTER_SALARY_MAGMA'),
    path('IDFC_HL_BILLING/', views.IDFC_HL_BILLING, name='IDFC_HL_BILLING'),
    # path('FULLERTON_OTR_MIS/', views.FULLERTON_OTR_MIS, name='FULLERTON_OTR_MIS'),
    # path('FULLERTON_OTR_BILLING/', views.FULLERTON_OTR_BILLING, name='FULLERTON_OTR_BILLING'),
    # path('FULLERTON_RECOVERY_MIS/', views.FULLERTON_RECOVERY_MIS, name='FULLERTON_RECOVERY_MIS'),
    # path('FULLERTON_RECOVERY_SALARY/', views.MASTER_SALARY_FULLERTON, name='MASTER_SALARY_FULLERTON'),
    # path('FULLERTON_RECOVERY_BILLING/', views.FULLERTON_RECOVERY_BILLING, name='FULLERTON_RECOVERY_BILLING'),
    # path('FULLERTON_OTR_MIS/FULLERTON_FR_MIS/', views.FULLERTON_FR_MIS, name='FULLERTON_FR_MIS'),
    # path('FULLERTON_OTR_BILLING/FULLERTON_FR_BILLING', views.FULLERTON_FR_BILLING, name='FULLERTON_FR_BILLING'),
    path('login/BAJAJ_MIS.html', views.BAJAJ_MIS, name='BAJAJ_MIS'),
    path('login/MAGMA_MIS.html', views.MAGMA_MIS, name='MAGMA_MIS'),
    path('BAJAJ_PL_MIS/', views.BAJAJ_PL_MIS, name='BAJAJ_PL_MIS'),
    path('BAJAJ_CD_BILLING/', views.BAJAJ_BILLING, name='BAJAJ_BILLING'),
    path('MAGMA_BILLING/', views.MAGMA_BILLING, name='MAGMA_BILLING'),
    path('SLICE_CC_BILLING/', views.SLICE_BILLING, name='SLICE_BILLING'),
    # path('BAJAJ_CD_SALARY/', views.BAJAJ_SALARY, name='BAJAJ_SALARY'),
    path('Employee_database/', views.employee_database, name='employee_database'),
    # path('down/', views.L_T_PERFORMANCE_DOWNLOAD, name='L_T_DOWNLOAD'),
    path('down1/', views.IDFC_TW_PERFORMANCE_DOWNLOAD, name='IDFC_TW_DOWNLOAD'),
    path('down99/', views.IDFC_TW_MASTER_DOWNLOAD, name='IDFC_TW_MASTER_DOWNLOAD'),
    path('down2/', views.IDFC_HL_PERFORMANCE_DOWNLOAD, name='IDFC_HL_DOWNLOAD'),
    # path('down3/', views.FULLERTON_OTR_PERFORMANCE_DOWNLOAD, name='FULLERTON_OTR_DOWNLOAD'),
    # path('down4/', views.FULLERTON_RECOVERY_PERFORMANCE_DOWNLOAD, name='FULLERTON_RECOVERY_DOWNLOAD'),
    # path('down24/', views.FULLERTON_RECOVERY_BILLING_DOWNLOAD, name='FULLERTON_BILLING_DOWNLOAD'),
    # path('down25/', views.FULLERTON_RECOVERY_SALARY_DOWNLOAD, name='FULLERTON_SALARY_DOWNLOAD'),
    path('down5/', views.BAJAJ_CD_PERFORMANCE_DOWNLOAD, name='BAJAJ_CD_DOWNLOAD'),
    path('login/MAGMA_MIS.html', views.MAGMA_MIS, name='MAGMA_MIS'),
    path('MAGMA_BILLING/', views.MAGMA_BILLING, name='MAGMA_BILLING'),
    # path('down6/', views.L_T_BILLING_DOWNLOAD, name='L_T_BILLING_DOWNLOAD'),
    path('down7/', views.IDFC_TW_BILLING_DOWNLOAD, name='IDFC_TW_BILLING_DOWNLOAD'),
    path('down8/', views.IDFC_HL_BILLING_DOWNLOAD, name='IDFC_HL_BILLING_DOWNLOAD'),
    # path('down9/', views.FULLERTON_OTR_PERFORMANCE_DOWNLOAD, name='FULLERTON_OTR_DOWNLOAD'),
    # path('down10/', views.FULLERTON_RECOVERY_PERFORMANCE_DOWNLOAD, name='FULLERTON_RECOVERY_DOWNLOAD'),
    path('down11/', views.BAJAJ_CD_BILLING_DOWNLOAD, name='BAJAJ_CD_BILLING_DOWNLOAD'),
    # path('down12/', views.L_T_SALARY_FIXED_DOWNLOAD, name='L_T_SALARY_FIXED_DOWNLOAD'),
    # path('down13/', views.L_T_SALARY_INCENTIVE_PIVOT_DOWNLOAD, name='L_T_SALARY_INCENTIVE_PIVOT_DOWNLOAD'),
    # path('down14/', views.L_T_SALARY_INCENTIVE_DOWNLOAD, name='L_T_SALARY_INCENTIVE_DOWNLOAD'),
    path('down15/', views.IDFC_TW_SALARY_FIXED_DOWNLOAD, name='IDFC_TW_SALARY_FIXED_DOWNLOAD'),
    path('down16/', views.IDFC_TW_SALARY_INCENTIVE_PIVOT_DOWNLOAD, name='IDFC_TW_SALARY_INCENTIVE_PIVOT_DOWNLOAD'),
    path('down17/', views.IDFC_TW_SALARY_INCENTIVE_DOWNLOAD, name='IDFC_TW_SALARY_INCENTIVE_DOWNLOAD'),
    path('down18/', views.BAJAJ_CD_SALARY_DOWNLOAD, name='BAJAJ_CD_SALARY_DOWNLOAD'),
    path('down19/', views.IDFC_HL_SALARY_DOWNLOAD, name='IDFC_HL_SALARY_DOWNLOAD'),
    path('down20/', views.IDFC_HL_TL_INCENTIVE_DOWNLOAD, name='IDFC_HL_TL_INCENTIVE_DOWNLOAD'),
    path('down21/', views.IDFC_HL_FINAL_SALARY_INCENTIVE_DOWNLOAD, name='IDFC_HL_FINAL_SALARY_INCENTIVE_DOWNLOAD'),
    path('down22/', views.IDFC_TW_TC_SALARY_DOWNLOAD, name='IDFC_TW_TC_SALARY_DOWNLOAD'),
    path('down23/', views.BAJAJ_PL_BILLING_DOWNLOAD, name='BAJAJ_PL_BILLING_DOWNLOAD'),
    path('down24/', views.BAJAJ_PL_PERFORMANCE_DOWNLOAD, name='BAJAJ_PL_PERFORMANCE_DOWNLOAD'),
    path('down25/', views.BAJAJ_CD_MASTER_DOWNLOAD, name='BAJAJ_CD_MASTER_DOWNLOAD'),
    path('down26/', views.BAJAJ_PL_MASTER_DOWNLOAD, name='BAJAJ_PL_MASTER_DOWNLOAD'),
    path('down27/', views.MAGMA_FOS_SALARY_DOWNLOAD, name='MAGMA_FOS_SALARY_DOWNLOAD'),
    path('down28/', views.SLICE_FOS_SALARY_DOWNLOAD, name='SLICE_FOS_SALARY_DOWNLOAD'),
    path('down29/', views.SLICE_FOS_SALARY_PER_PAID_CASE_DOWNLOAD, name='SLICE_FOS_SALARY_PER_PAID_CASE_DOWNLOAD'),
    path('down30/', views.SLICE_MASTER_FILE_DOWNLOAD, name='SLICE_MASTER_FILE_DOWNLOAD'),
    path('down31/', views.MAGMA_MASTER_FILE_DOWNLOAD, name='MAGMA_MASTER_FILE_DOWNLOAD'),
    # path('down23/', views.L_T_TC_SALARY_DOWNLOAD, name='L_T_TC_SALARY_DOWNLOAD'),
    path('login/NAV.html', views.NAV, name='NAV'),
    # path('login/salary.html', views.MASTER_SALARY_TW, name='L_T_TW'),
    path('bajaj_salary/', views.BAJAJ_SALARY, name='BAJAJ_SALARY'),
    path('login/bajaj_salary1.html', views.BAJAJ_PL_SALARY, name='BAJAJ_PL_SALARY'),
    # path('login/IDFC-HL_Salary.html', views.MASTER_SALARY_IDFC, name='IDFC_HL_SALARY'),
    path('IDFC-HL_Salary/', views.MASTER_SALARY_IDFC, name='IDFC_HL_SALARY'),
    path('SLICE-CC_Salary/', views.MASTER_SALARY_SLICE, name='MASTER_SALARY_SLICE'),
    # path('login/FULLERTON_RECOVERY_SALARY.html', views.MASTER_SALARY_FULLERTON, name='MASTER_SALARY_FULLERTON'),
    path('login/IDFC_TW_TL_ANALYSIS.html', views.IDFC_TW_TL_ANALYSIS, name='IDFC_TW_TL_ANALYSIS'),
    path('TL_SALARY/', views.IDFC_TW_TL_SALARY, name='IDFC_TW_TL_SALARY'),
    path('Active_IDFC_TW_employees/', views.IDFC_TW_EMPLOYEES, name='IDFC_TW_EMPLOYEES'),
    # path('Active_FULLERTON_RECOVERY_employees/', views.FULLERTON_RECOVERY_EMPLOYEES, name='FULLERTON_RECOVERY_EMPLOYEES'),
    path('Active_IDFC_HL_employees/', views.IDFC_HL_EMPLOYEES, name='IDFC_HL_EMPLOYEES'),
    path('Active_BAJAJ_CD_employees/', views.BAJAJ_CD_EMPLOYEES, name='BAJAJ_CD_EMPLOYEES'),
    path('IDFC_TW_ANALYSIS/', views.IDFC_TW_ANALYSIS, name='IDFC_TW_ANALYSIS'),
    path('SLICE_CC_ANALYSIS/', views.SLICE_AUTO_ANALYSIS, name='SLICE_AUTO_ANALYSIS'),
    # path('FULLERTON_RECOVERY_ANALYSIS/', views.FULLERTON_RECOVERY_ANALYSIS, name='FULLERTON_RECOVERY_ANALYSIS'),
    path('BAJAJ_CD_ANALYSIS/', views.BAJAJ_CD_ANALYSIS, name='BAJAJ_CD_ANALYSIS'),
    path('IDFC_HL_ANALYSIS/', views.IDFC_HL_ANALYSIS, name='IDFC_HL_ANALYSIS'),
    path('MAGMA_AUTO_ANALYSIS/', views.MAGMA_AUTO_ANALYSIS, name='MAGMA_AUTO_ANALYSIS'),
    path('login/FOS_COMBINED_MIS.html', views.FOS_COMBINED_SALARY, name='combined_salary'),
]

FirstLevel/models.py
from django.db import models
# Create your models here.


class UserProfileInfo(models.Model):
    # create relationship(don't inherit from User!)

    # Add any additional attributes you want
    # These name should be similar to the names in forms.py
    username = models.CharField(max_length=30, blank=False, unique=True)
    email = models.EmailField(max_length=60, blank=False, unique=True)
    confirm_email = models.EmailField(blank=False, unique=True)
    password = models.CharField(max_length=30, blank=False)
    confirm_password = models.CharField(max_length=30, blank=False)
    birth_date = models.DateField(blank=False)
    First_Name = models.CharField(max_length=30, blank=False)
    Last_Name = models.CharField(max_length=30, blank=False)
    Emp_ID = models.CharField(max_length=6, blank=False, unique=True)

    def __str__(self):
        return self.username+','+self.password+','+self.Emp_ID

    @classmethod
    def get(cls, param):
        pass

class loginpage(models.Model):
    password = models.CharField(max_length=30, blank=False)
    username = models.CharField(max_length=30, blank=False)
    Emp_ID = models.CharField(max_length=6, blank=True)


class Employee(models.Model):
    NAMES = models.CharField(max_length=50, unique=True, null=False)
    EMPLOYEE_ID = models.CharField(max_length=4, unique=True, null=False)
    MANAGER_ID = models.CharField(max_length=4, null=True)
    MANAGEMENT_LEVEL = models.CharField(max_length=20, null=False)
    DESIGNATION = models.CharField(max_length=20, null=False)
    STAFF = models.CharField(max_length=7 ,null=False)
    EMPLOYEE_STATUS = models.CharField(max_length=20, null=False)
    PROCESS = models.CharField(max_length=20, null=False)
    DEPARTMENT = models.CharField(max_length=15, null=False)
    TYPE_OF_SALARY = models.CharField(max_length=30, null=False)
    SALARY = models.IntegerField(null=False)
    DATE_OF_BIRTH = models.DateField(null=False)
    LOCATION_ID = models.CharField(max_length=10, null=True)
    PHONE_NUMBER = models.IntegerField(null=False)
    HIRE_DATE = models.DateField(null=False)
    END_DATE = models.DateField(null=True)
    DEPARTMENT_ID = models.CharField(max_length=10,null=True)

FirstLevel/forms.py
from django import forms
from .models import UserProfileInfo, loginpage, Employee
# we always use .models or .forms to import data from models or forms respectively

YEARS = [x for x in range(1940,2021)]

class UserForm(forms.ModelForm):
    username = forms.CharField()
    email = forms.EmailField()
    confirm_email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())
    birth_date = forms.DateField(widget=forms.SelectDateWidget(years=YEARS))
    First_Name = forms.CharField()
    Last_Name = forms.CharField()
    Emp_ID = forms.CharField()
    class Meta():
        model = UserProfileInfo
        fields = '__all__'

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vemail = all_clean_data['confirm_email']
        password = all_clean_data['password']
        vpassword = all_clean_data['confirm_password']
        emp_id = all_clean_data['Emp_ID']
        date_of_birth = all_clean_data['birth_date']

        if (vpassword != password) or (email != vemail):
            raise forms.ValidationError('')
        elif (vpassword == password) or (email == vemail):
            EE = Employee.objects.order_by('NAMES')
            for E in EE:
                employeeid = E.EMPLOYEE_ID
                dateofbirth = E.DATE_OF_BIRTH
                print(employeeid)
                print(dateofbirth)
                if (emp_id != employeeid) or (date_of_birth != dateofbirth):
                    continue
                else:
                    return
            raise forms.ValidationError('')

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())
    Emp_ID = forms.CharField()

    class Meta():
        model3 = loginpage
        fields3 = ('password', 'username', 'Emp_ID')

    def clean(self):
        all_clean_data = super().clean()
        Emp_ID = all_clean_data['Emp_ID']
        username = all_clean_data['username']
        password = all_clean_data['password']
        print(Emp_ID, username, password)

        # Taking out data from the pre saved database of UserProfileInfo
        username1 = UserProfileInfo.objects.order_by('username')
        for u in username1:
            username11 = u.username
            password1 = u.password
            Emp_ID1 = u.Emp_ID
            print(username11)
            print(password1)
            print(Emp_ID1)
            if (password != password1) or (username != username11) or (Emp_ID != Emp_ID1):
                continue
            else:
                return True
        raise forms.ValidationError('')

templates/FirstLevel/clients.html
{% extends 'FirstLevel/base.html' %}
{% load static %}
{% block body_block %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width , initial- scale 1.0">
    <title></title>
    <link rel="stylesheet" href="{% static 'FirstLevel/css/clients.css' %}">
</head>
<body>
<SECTION class="course">
    <H1 style="margin-bottom:0px; margin-top:52px">OUR CLIENTS</H1>
    <HR color= #d3ae6d>
    <OL class="breadcrumb" style="margin-top:0px;margin-bottom:0px;padding-left:0px;padding-top:0px;">
        <LI>
            <A href="{% url 'basic_app:index' %}">Home</A>
        </LI>
        <LI>
            <A href="{% url 'basic_app:clients' %}">Our Clients</A>
        </LI>
    </OL>

    <DIV class="row">
        <DIV class="course-col">
            <H3>IDFC CAPITAL FIRST</H3>
            <IMG class="idfc" src="{% static 'FirstLevel/images/idfc logo.png' %}" alt="">
                <P>IDFC Bank is a universal bank , offering financial solutions through its nationwide branches ,
                    internet and mobile. IDFC Bank offers basic services like savings account , NRI Accounts ,
                    Fixed Deposits , Home Loan , Personal loan among others , using technology and a
                    service - oriented approach , to make banking simple and accessible , anytime and from anywhere.
                </P>
        </DIV>

        <DIV class="course-col">
            <H3>BAJAJ FINSERV</H3>
            <IMG class="idfc" src="{% static 'FirstLevel/images/bajaj.jpg' %}" alt="">
                <P> Bajaj Finserv, is an Indian non-banking financial company (NBFC). The company deals in consumer
                    finance, SME (small and medium-sized enterprises) and commercial lending, and wealth management.
                </P>
        </DIV>

        <DIV class="course-col">
            <H3>L&T Financial Services </H3>
            <IMG class="idfc" src="{% static 'FirstLevel/images/l&t logo.png' %}" alt="">
                <P> L&T Finance Holdings Ltd. is a NSE and BSE listed company and is also registered with RBI as an
                    NBFC and CIC. It conducts its financial services businesses through various subsidiaries.
                    L&T Financial Services is the brand name of L&T Finance Holdings Ltd.
                </P>
        </DIV>
    </DIV>

    <DIV class="row2">
        <DIV class="course-col">
            <H3>KOTAK MAHINDRA</H3>
            <IMG class="idfc" src="{% static 'FirstLevel/images/kotak.png' %}" alt="">
                <P>Kotak Mahindra Bank Limited is an Indian private sector bank headquartered in Mumbai,
                    Maharashtra, India. It offers banking products and financial services for corporate and
                    retail customers in the areas of personal finance, investment banking, life insurance,
                    and wealth management.
                </P>
        </DIV>

        <DIV class="course-col">
            <H3>FULLERTON INDIA</H3>
            <IMG class="idfc" src="{% static 'FirstLevel/images/flurtron.png' %}" alt="">
                <P>Fullerton India Credit Co. Ltd. is a non - banking financial company in India.
                    It is headquartered at Mumbai, India and deals with financing across retail and rural segments.
                    The company provides unsecured as well as secured lending products through a diverse branch network
                    as well as via digital channels to individuals and MSMEs
                </P>
        </DIV>
    </DIV>
</SECTION>
</body>
</html>
{% endblock %}

<!--CLIENTS?-->

templates/FirstLevel/employee_database.html
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{message.tag}}" role="alert">
    <p {% if message.tags %} class=""{% endif %}>{{message}}</p>
</div>
{% endfor %}
{% endif %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="employee">
    <button type="submit">Employee Database Upload</button>
</form>

templates/FirstLevel/login.html
{% extends 'FirstLevel/base.html' %}
{% load static %}
{% block body_block %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'FirstLevel/css/login.css' %}">
</head>
<body>

        <H1 class='gos'>COMPANY LOGIN</H1>

        <FORM class="boxx" action="{% url 'basic_app:user_login' %}" method="POST">
            {% csrf_token %}
            {{login_form.as_p}}
                <TABLE>
                    <TH>
                        <STRONG><INPUT type="submit" name="" value="LOGIN"></STRONG>
                    </TH>

                    <TH>
                        <A href="{% url 'basic_app:register' %}">New User?</A>
                    </TH>
                </TABLE>
        </FORM>


    <H4 class="error">
        {{Error}}
        {{re}}
    </H4>
    <img class="princ" src="{% static 'FirstLevel/images/4ps.png' %}">

</body>
</html>
{% endblock %}

templates/FirstLevel/login_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="HandheldFriendly" content="true">
    <link rel="stylesheet" href="{% static 'FirstLevel/css/base.css' %}">
</head>
<body style="padding-top:8px;">
    <NAV>
        <div class="logo" style="height:0px">
            <A href="{% url 'basic_app:index' %}">
                <IMG SRC= "{% static 'FirstLevel/images/logo.png' %}">
            </A>
        </div>
        <label for="btn" class="icon">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
        </label>
        <input type="checkbox" id="btn">
        <UL class="nav">
            <LI>
                <A HREF="{% url 'basic_app:index' %}" style="padding-left:0px"><strong>HOME</strong></A>
            </LI>
            <LI>
                <A HREF="{% url 'basic_app:vision' %}" style="padding-left:0px"><strong>VISION / MISSION</strong></A>
            </LI>
            <LI>
                <A HREF= "#" style="padding-left:0px"><strong>ABOUT US</strong></A>
                <UL class="drop">
                    <LI>
                        <A HREF= "#" style="padding-left:0px"><strong>OUR STRENGTH</strong></A>
                    </LI>
                    <LI>
                        <A HREF= "{% url 'basic_app:principle' %}" style="padding-left:0px"><strong>OUR PRINCIPLES</strong></A>
                    </LI>
                    <LI>
                        <A HREF= "{% url 'basic_app:clients' %}" style="padding-left:0px"><strong>OUR CLIENTS</strong></A>
                    </LI>
                </UL>
            </LI>
            <LI>
                <a href="{% url 'basic_app:whatwedo' %}" style="padding-left:0px"><strong>WHAT WE DO !</strong></a>
            </LI>
            <LI >
                <A HREF= "#" style="padding-left:0px"><strong>CONTACT US</strong></a>
                <UL class="drop">
                    <LI>
                        <A HREF= "#" style="padding-left:0px"><strong>DIRECTORS</strong></A>
                    </LI>
                    <LI>
                        <A HREF= "#" style="padding-left:0px"><strong>WANT TO JOIN</strong></A>
                    </LI>
                    <LI>
                        <A HREF= "#" style="padding-left:0px"><strong>PARTNER WITH US</strong></A>
                    </LI>
                </UL>
            </LI>
            <UL class="log">
                <A HREF="{% url 'basic_app:user_login' %}"><strong>LOGIN</strong></A>
            </UL>
        </UL>
    </NAV>
      {% block body_block %}

      {% endblock %}
</body>
</html>
<!--LOGIN BASE-->

templates/FirstLevel/whatwedo.html
{% extends 'FirstLevel/base.html' %}
{% load static %}
{% block body_block %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'FirstLevel/css/whatwedo.css' %}">
    <title>WHAT WE DO</title>
</head>
<body>
  <h1 style="margin-bottom:0px;margin-top:0px;border-left-style:solid;border-left-width:0px; margin-left:110px; color:white">WHAT WE DO</h1>
  <hr color="#d3ae6d" style="margin-left:115px; margin-right:50px;">
  <ol class="breadcrumb" style="width:400px;padding-bottom:10px;padding-left:20px;padding-top:0px;margin-top:0px;">
    <li>
      <a href="{% url 'basic_app:index' %}" style="padding-left:75px;" >Home</a>
    </li>
    <li>
      <a href="{% url 'basic_app:whatwedo' %}">What We Do</a>
    </li>
  </ol>
  <section class="service">
    <div class="first">
      <img class="img1" src="{% static 'FirstLevel/images/Picture1.png' %}" alt="">
      <img class="img2" src="{% static 'FirstLevel/images/Picture2.png' %}" alt="">
    </div>

    <div class="second">
        <img class="img3" src="{% static 'FirstLevel/images/Picture3.png' %}" alt="">
    </div>

    <div class="third">
        <img class="img4" src="{% static 'FirstLevel/images/Picture4.png' %}" alt="">
        <img class="img5" src="{% static 'FirstLevel/images/Picture5.png' %}" alt="">
    </div>
  </section>
</body>
</html>
{% endblock %}